// Run 'dbdocs build ./Database.dbml'
// Project name: Athletic Form Database

Table Schedule {
    EventID int [pk, not null]
    DepartureTime date [not null]
    TeamName varchar(20) [not null]
}

Table Teams {
    TeamName varchar(20) [pk, not null]
    CoachFirstName varchar(20)
    CoachLastName varchar(20)
    CoachEmail varchar(52)
}

Table StudentTeams {
    TeamName varchar(20) [pk, not null]
    StudentID long [not null]
}

Table Students {
    StudentID long [pk, not null]
    FirstName varchar(20) [not null]
    LastName varchar(20) [not null]
    Email varchar(52) [not null]
}

Table StudentCourses {
    StudentID long [pk, not null]
    CourseCode varchar(7)
}

Table Courses {
    CourseCode varchar(7) [pk]
    CourseName varchar(20) 
    Time time
    ProfessorID long
}

Table Professors {
    ProfessorID long [pk]
    FirstName varchar(20)
    LastName varchar(20)
    Email varchar(52)
    PhoneNumber varchar(10)
}


// Foreign Keys
Ref: StudentCourses.StudentID > Students.StudentID
Ref: StudentCourses.CourseCode > Courses.CourseCode
Ref: Courses.ProfessorID > Professors.ProfessorID
Ref: StudentTeams.StudentID > Students.StudentID
Ref: Teams.TeamName > StudentTeams.TeamName
Ref: Schedule.TeamName > Teams.TeamName